### ISSUE TITLE
Error connecting to Your ARIA2 Instance

### ISSUE THREAD

**Issue by kirincorleone** [hyperbunny77/RealDebridManager#15]
My RDM is refusing to connect with Aria2-pro, even though Ariang was able to connect without any issues. The logs just say Error connecting to Your ARIA2 Instance. I have tried entering multiple times in the Aria2 Host Location as follows:

(Everything is a separate docker container)

1. http://ip:port1/jsonrpc
2. http://ip:port1/rpc
3. http://ip:port2/
4. http://ip:port2
5. http://ip
6. ip:port

I have also tried:
1. Different ports on both RDM & Aria2-pro. Ariang was always able to connect with Aria2-pro without fail.
2. IPv6
3. Host Network - all
4. Bridge Network - all

I have verified my secret key many a times. It is correctly entered. 

I do not know what else I can do, except ask here.

**Comment by kirincorleone** [comment]
I fixed it. I had to manually add the subnet to gluetun's firewall.

**Comment by mareczek82** [comment]
c

> I fixed it. I had to manually add the subnet to gluetun's firewall.

coudl you describe how you did it? i have same problem

**Comment by kirincorleone** [comment]
Hey, 

I solved it by putting the local ip address of the docker network. Both RDM & Aria2+ng share the docker bridge network. 
I input the ip in RDM settings like this: http://local-docker-network-ip (no slash, no colon, no port, no text in the end)

The Aria-rpc port is hard coded in rdm so dont change it. You can change aria-ng's web port to whatever you want. 

Also I am not sure if it needed after using the local docker network ip but since I am also using gluetun (separate docker network now), I added the local lan ip and the local docker network ip into the firewall outbound subnets of gluetun.
