### ISSUE TITLE
Feature: use RD to download but leave it

### ISSUE THREAD

**Issue by kennyparsons** [hyperbunny77/RealDebridManager#56]
My current flow is to use Real Debrid and mount it to Plex with rclone-rd. Obviously, this is different than the typical *Arr user. Instead of using aria to download, I like to keep the files in RD and mount the files to Plex. 

My ideal workload would be to use RDM as a shim for an indexer. Then as a shim for a downloader. In this new mode, call it cache mode, aria would not be called. 

Do you think this is something we could work out and plan out?

**Comment by Oorweeg** [comment]
fwiw, I think rdt-client (https://github.com/rogerfar/rdt-client) has the functionality you need already
