### ISSUE TITLE
Alldebrid support + blackhole issue

### ISSUE THREAD

**Issue by janaxhell** [hyperbunny77/RealDebridManager#7]
Hi, you told me to DM you on reddit, but then disappeared, so here I am. It was about adding Alldebrid support and testing it. Looking at the description you still haven't added it, but I see something that I would consider an issue already: the exclusive use of blackhole.
rdt-client has the option to choose whether to download everything it finds in blackhole/*debrid OR download only IF request is coming from *arrs and ignore the rest. 
I often download stuff that has nothing to do with my *arr server, so I don't want rdt-client to download it to the server as soon as it sees it in blackhole/alldebrid. This way what must go to *arr server goes there and the rest is manually downloaded by me to my PC.
Maybe you already has set it this way, but having Alldebrid only I cannot try it.

**Comment by hyperbunny77** [comment]
Closing issue. - Communicating via Reedit. Support for this is being added via a new release.
